var products = {
    "p1":{
        img:"images/product/1.jpg",
        name:"Applied Biosystems QuantStudio 6/7 Pro 智能实时荧光定量PCR系统",
        intro:"Applied BiosystemsTM    QuantStudioTM    6/7 Pro 实时荧光定量PCR系统提供智能化工作流程体验，满足各种检测需求，为实验室研究带来革新性qPCR检测。",
        feature:"多种应用：病原体筛查与鉴定、传染性疾病、病毒载量分析、药物代谢、植物科学、肿瘤学等等<br>全面智能化升级：触屏控制，人脸识别，语音控制，射频标签检测<br>支持远程连接访问：基于云平台实时进行信息访问、存储和在线共享<br>硬件配置更新：5或6个光学通道，全新光源与加热硬件系统<br>支持各种通量模块：最多支持4种不同通量模块，包括96，96快速，384以及TAC模块，适应多种实验场景需求<br>结果稳定可靠：10 个对数单位的动态范围，检测差异低至 1.5 倍",
        type:1,
        url:"http://cdn.dhteam.net/juze/smf/G4 冷冻透射电子显微镜.pdf"
    },
    "p2":{
        img:"sssss",
        name:"sssss",
        intro:"sssss",
        feature:"sssss",
        type:1,
        url:"sssss"
    },
    "p3":{
        img:"sssss",
        name:"sssss",
        intro:"sssss",
        feature:"sssss",
        type:1,
        url:"sssss"
    },
    "p4":{
        img:"sssss",
        name:"sssss",
        intro:"sssss",
        feature:"sssss",
        type:1,
        url:"sssss"
    },
    "p5":{
        img:"sssss",
        name:"sssss",
        intro:"sssss",
        feature:"sssss",
        type:1,
        url:"sssss"
    },
    "p6":{
        img:"sssss",
        name:"sssss",
        intro:"sssss",
        feature:"sssss",
        type:1,
        url:"sssss"
    },
    "p7":{
        img:"sssss",
        name:"sssss",
        intro:"sssss",
        feature:"sssss",
        type:1,
        url:"sssss"
    },
    "p8":{
        img:"sssss",
        name:"sssss",
        intro:"sssss",
        feature:"sssss",
        type:1,
        url:"sssss"
    },
    "p9":{
        img:"sssss",
        name:"sssss",
        intro:"sssss",
        feature:"sssss",
        type:1,
        url:"sssss"
    },
    "p10":{
        img:"sssss",
        name:"sssss",
        intro:"sssss",
        feature:"sssss",
        type:1,
        url:"sssss"
    },
    "p11":{
        img:"sssss",
        name:"sssss",
        intro:"sssss",
        feature:"sssss",
        type:1,
        url:"sssss"
    },
    "p12":{
        img:"sssss",
        name:"sssss",
        intro:"sssss",
        feature:"sssss",
        type:1,
        url:"sssss"
    },
    "p13":{
        img:"sssss",
        name:"sssss",
        intro:"sssss",
        feature:"sssss",
        type:1,
        url:"sssss"
    },
    "p14":{
        img:"sssss",
        name:"sssss",
        intro:"sssss",
        feature:"sssss",
        type:1,
        url:"sssss"
    },
    "p15":{
        img:"sssss",
        name:"sssss",
        intro:"sssss",
        feature:"sssss",
        type:1,
        url:"sssss"
    },
    "p16":{
        img:"sssss",
        name:"sssss",
        intro:"sssss",
        feature:"sssss",
        type:1,
        url:"sssss"
    },
    "p17":{
        img:"sssss",
        name:"sssss",
        intro:"sssss",
        feature:"sssss",
        type:1,
        url:"sssss"
    },
    "p18":{
        img:"sssss",
        name:"sssss",
        intro:"sssss",
        feature:"sssss",
        type:1,
        url:"sssss"
    },
    "p19":{
        img:"sssss",
        name:"sssss",
        intro:"sssss",
        feature:"sssss",
        type:1,
        url:"sssss"
    },
    "p20":{
        img:"sssss",
        name:"sssss",
        intro:"sssss",
        feature:"sssss",
        type:1,
        url:"sssss"
    },
    "p21":{
        img:"sssss",
        name:"sssss",
        intro:"sssss",
        feature:"sssss",
        type:1,
        url:"sssss"
    },
    "p22":{
        img:"sssss",
        name:"sssss",
        intro:"sssss",
        feature:"sssss",
        type:1,
        url:"sssss"
    },
    "p23":{
        img:"sssss",
        name:"sssss",
        intro:"sssss",
        feature:"sssss",
        type:1,
        url:"sssss"
    },
    "p24":{
        img:"sssss",
        name:"sssss",
        intro:"sssss",
        feature:"sssss",
        type:1,
        url:"sssss"
    },
    "p25":{
        img:"sssss",
        name:"sssss",
        intro:"sssss",
        feature:"sssss",
        type:1,
        url:"sssss"
    },
    "p26":{
        img:"sssss",
        name:"sssss",
        intro:"sssss",
        feature:"sssss",
        type:1,
        url:"sssss"
    },
    "p27":{
        img:"sssss",
        name:"sssss",
        intro:"sssss",
        feature:"sssss",
        type:1,
        url:"sssss"
    },
    "p28":{
        img:"sssss",
        name:"sssss",
        intro:"sssss",
        feature:"sssss",
        type:1,
        url:"sssss"
    },
    "p29":{
        img:"sssss",
        name:"sssss",
        intro:"sssss",
        feature:"sssss",
        type:1,
        url:"sssss"
    }
}